/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String POPPINS_BOLD = 'Poppins-Bold';
  static const String POPPINS_ITALIC = 'Poppins-Italic';
  static const String POPPINS_LIGHT = 'Poppins-Light';
  static const String POPPINS_MEDIUM = 'Poppins-Medium';
  static const String POPPINS_MEDIUMITALIC = 'Poppins-MediumItalic';
  static const String POPPINS_REGULAR = 'Poppins-Regular';
  static const String POPPINS_SEMIBOLD = 'Poppins-SemiBold';
}
