// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoKhv7xna2w-Gjbo1MsVo8DY5dGHEkdIU',
    appId: '1:718876036888:web:80bb3a3c4a0c1fa0d4d86d',
    messagingSenderId: '718876036888',
    projectId: 'e-commerce-app-a468c',
    authDomain: 'e-commerce-app-a468c.firebaseapp.com',
    storageBucket: 'e-commerce-app-a468c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3le4AQcm7cQ28kFSVXKPq52dhlqNZ4j8',
    appId: '1:718876036888:android:12dcbf65af79d192d4d86d',
    messagingSenderId: '718876036888',
    projectId: 'e-commerce-app-a468c',
    storageBucket: 'e-commerce-app-a468c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMnN6vhyDxN_BHBF_GDLd2zmDpbGyJ_oM',
    appId: '1:718876036888:ios:e60a7327dc51fc17d4d86d',
    messagingSenderId: '718876036888',
    projectId: 'e-commerce-app-a468c',
    storageBucket: 'e-commerce-app-a468c.appspot.com',
    androidClientId: '718876036888-uqi9jpu1chdnin79qrtt53t8ls0tqe94.apps.googleusercontent.com',
    iosClientId: '718876036888-6kj12oc8ge45ds037m1kuo3qudm2eo5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );
}
